# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caa87d532c298d955a4e86057d503c4f3c9337aa0b9e29daab562f02d69e56f2262923519d1a99ac1cd725edc447ec33b5f7d3f0016e22cd7fd89f555900b81e

test:
  secret_key_base: aaa16d9b50e47ea5570549d98e7ed9338bd5e43b4eb1d41d216ab3c1987f64cd6267c717a9e9577567469d3c58ebb38b349d057876305e0bd5e335beed281b2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
